### ISSUE TITLE
Please rename default branch to main

### ISSUE THREAD

**Issue by JayamalHettiarachchi** [Typefi-Systems/adobe-community-scripts#1]
This is related to https://github.com/typefi/devops/issues/2.

**Comment by JayamalHettiarachchi** [comment]
Hi @benhauser,
Can you please grant me admin access to get this done?
Thanks.

**Comment by dinesh-amarasekara** [comment]
Hi @JayamalHettiarachchi,

OK. Granted the admin rights. Please proceed.

Dinesh.

**Comment by JayamalHettiarachchi** [comment]
Thank you @dinesh-amarasekara,
Renamed.
